/// XMPP namespace constants per RFC 6120.
public enum XMPPNamespaces {
    public static let streams = "urn:ietf:params:xml:ns:xmpp-streams"
    public static let stanzas = "urn:ietf:params:xml:ns:xmpp-stanzas"
    public static let tls = "urn:ietf:params:xml:ns:xmpp-tls"
    public static let bind = "urn:ietf:params:xml:ns:xmpp-bind"
    public static let session = "urn:ietf:params:xml:ns:xmpp-session"
    public static let roster = "jabber:iq:roster"
    public static let rosterVersioning = "urn:xmpp:features:rosterver"
    public static let preApproval = "urn:xmpp:features:pre-approval"
    public static let discoInfo = "http://jabber.org/protocol/disco#info"
    public static let discoItems = "http://jabber.org/protocol/disco#items"
    public static let caps = "http://jabber.org/protocol/caps"
    public static let vcard = "vcard-temp"
    public static let carbons = "urn:xmpp:carbons:2"
    public static let forward = "urn:xmpp:forward:0"
    public static let mam = "urn:xmpp:mam:2"
    public static let mamExtended = "urn:xmpp:mam:2#extended"
    public static let sm = "urn:xmpp:sm:3"
    public static let ping = "urn:xmpp:ping"
    public static let delay = "urn:xmpp:delay"
    public static let rsm = "http://jabber.org/protocol/rsm"
    public static let stanzaID = "urn:xmpp:sid:0"
    public static let receipts = "urn:xmpp:receipts"
    public static let chatMarkers = "urn:xmpp:chat-markers:0"
    public static let chatStates = "http://jabber.org/protocol/chatstates"
    public static let messageCorrect = "urn:xmpp:message-correct:0"
    public static let messageReply = "urn:xmpp:reply:0"
    public static let muc = "http://jabber.org/protocol/muc"
    public static let mucUser = "http://jabber.org/protocol/muc#user"
    public static let mucAdmin = "http://jabber.org/protocol/muc#admin"
    public static let mucOwner = "http://jabber.org/protocol/muc#owner"
    public static let mucDirectInvite = "jabber:x:conference"
    public static let httpUpload = "urn:xmpp:http:upload:0"
    public static let dataForms = "jabber:x:data"
    public static let jingle = "urn:xmpp:jingle:1"
    public static let jingleFileTransfer = "urn:xmpp:jingle:apps:file-transfer:5"
    public static let jingleS5B = "urn:xmpp:jingle:transports:s5b:1"
    public static let jingleIBB = "urn:xmpp:jingle:transports:ibb:1"
    public static let bytestreams = "http://jabber.org/protocol/bytestreams"
    public static let ibb = "http://jabber.org/protocol/ibb"
    public static let blocking = "urn:xmpp:blocking"
    public static let pubsub = "http://jabber.org/protocol/pubsub"
    public static let pubsubEvent = "http://jabber.org/protocol/pubsub#event"
    public static let bookmarks2 = "urn:xmpp:bookmarks:1"
    public static let avatarData = "urn:xmpp:avatar:data"
    public static let avatarMetadata = "urn:xmpp:avatar:metadata"
    public static let vcardAvatarUpdate = "vcard-temp:x:update"
    public static let pepVCardConversion = "urn:xmpp:pep-vcard-conversion:0"
    public static let styling = "urn:xmpp:styling:0"
    public static let messageRetract = "urn:xmpp:message-retract:1"
    public static let messageModerate = "urn:xmpp:message-moderate:1"
    public static let fallbackIndication = "urn:xmpp:fallback:0"
    public static let processingHints = "urn:xmpp:hints"
    public static let oob = "jabber:x:oob"
    public static let oobIQ = "jabber:iq:oob"
    public static let serverInfo = "http://jabber.org/network/serverinfo"
    public static let channelSearch = "urn:xmpp:channel-search:0"
    public static let channelSearchQuery = "urn:xmpp:channel-search:0:search"
    public static let register = "jabber:iq:register"
    public static let registerFeature = "http://jabber.org/features/iq-register"
    public static let caps2 = "urn:xmpp:caps"
    public static let hashes2 = "urn:xmpp:hashes:2"
    public static let sasl2 = "urn:xmpp:sasl:2"
    public static let saslChannelBinding = "urn:xmpp:sasl-cb:0"
    public static let bind2 = "urn:xmpp:bind:0"
    public static let isr = "https://xmpp.org/extensions/isr/0"
    public static let isrMechanism = "HT-SHA-256-ENDP"
    public static let csi = "urn:xmpp:csi:0"

    // OMEMO (XEP-0384)
    public static let omemo = "urn:xmpp:omemo:2"
    public static let omemoDevices = "urn:xmpp:omemo:2:devices"

    /// Explicit Message Encryption (XEP-0380)
    public static let eme = "urn:xmpp:eme:0"

    /// Stanza Content Encryption (XEP-0420)
    public static let sce = "urn:xmpp:sce:1"

    /// Service Outage Status (XEP-0455)
    public static let serviceOutage = "urn:xmpp:service-outage:0"
}
