/// XMPP namespace constants per RFC 6120.
public enum XMPPNamespaces {
    public static let stream = "http://etherx.jabber.org/streams"
    public static let tls = "urn:ietf:params:xml:ns:xmpp-tls"
    public static let bind = "urn:ietf:params:xml:ns:xmpp-bind"
    public static let session = "urn:ietf:params:xml:ns:xmpp-session"
    public static let roster = "jabber:iq:roster"
    public static let discoInfo = "http://jabber.org/protocol/disco#info"
    public static let discoItems = "http://jabber.org/protocol/disco#items"
    public static let caps = "http://jabber.org/protocol/caps"
    public static let vcard = "vcard-temp"
    public static let carbons = "urn:xmpp:carbons:2"
    public static let forward = "urn:xmpp:forward:0"
    public static let mam = "urn:xmpp:mam:2"
    public static let sm = "urn:xmpp:sm:3"
    public static let ping = "urn:xmpp:ping"
    public static let delay = "urn:xmpp:delay"
    public static let rsm = "http://jabber.org/protocol/rsm"
    public static let stanzaID = "urn:xmpp:sid:0"
}
